name: lab_clinicas_core
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://www.example.com"
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  asyncstate: ^2.1.1-dev.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_getit: ^2.0.0
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.3
  signals: ^6.0.2
  top_snackbar_flutter: ^3.2.0